name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Lint
        run: make lint

      - name: Check format
        run: make check-format

      - name: Test
        run: make test

      - name: Create package
        run: make dist

      - name: Archive package artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:

      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Determine package name
        id: determine_package_name
        run: echo "::set-output name=package_name::$(ls -1 pyrake*.whl)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.determine_package_name.outputs.package_name }}
          asset_name: ${{ steps.determine_package_name.outputs.package_name }}
          asset_content_type: application/x-wheel+zip